[package]
name = "promo_codes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1

[dependencies]
axum = "^0.7.5"
axum-extra = { version = "0.9.3", features = ["cookie"] }
chrono = { version = "^0.4.38", features = ["serde"] }
pad = "^0.1.6"
rand = "^0.8.5"
serde = { version = "^1.0.209", features = ["derive"] }
serde_json = "^1.0.127"
sqlx = { version = "^0.8.1", features = ["runtime-tokio-native-tls", "postgres", "chrono"] }
tokio = { version = "^1.39.3", features = ["full"] }
tower-http = { version = "^0.5.2", features = ["fs", "trace"] }

[dev-dependencies]
cargo-husky = { version = "^1.5.0", default-features = false, features = ["user-hooks"] }
